apiVersion: v1
kind: Service
metadata:
  name: gnomeai-flask-service
spec:
  type: NodePort
  selector:
    app: gnomeai-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080