name: CI Pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t chillarneyman/hello-app:${{ github.sha }} .
      - name: push to docker hub
        run: docker push chillarneyman/hello-app:${{ github.sha }}
      - name: Update image tag in k8s config
        run: |
          sed -i 's/latest/${{ github.sha }}/g' k8s/deployment.yaml
          git commit -am "Update image tag"
          git push